export const SHOW_TOAST = 'SHOW_TOAST';
export const EXPAND_DRAWER = 'EXPAND_DRAWER';
export const EXPAND_DRAWER_TRIGGER = 'EXPAND_DRAWER_TRIGGER';
export const COLLAPSE_DRAWER = 'COLLAPSE_DRAWER';
export const COLLAPSE_DRAWER_TRIGGER = 'COLLAPSE_DRAWER_TRIGGER';
export const SHOW_LOADING = 'SHOW_LOADING';
